[package]
name = "composerr"
version = "0.2.2"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
thiserror = "1.0"

[lib]
proc-macro = true

[dev-dependencies]
thiserror = "1.0"
rand = "0.8.5"
