[package]
name = "composerr"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.36"
syn = { version = "2.0.63", features = ["full"] }

[lib]
proc-macro = true

[dev-dependencies]
thiserror = "1.0.60"
